apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: node-app
        image: harshp0207/adv-backend-metrics-application:latest
        ports:
        - containerPort: 7050
        env:
          - name: PORT
            value: "7050"
          - name: MONGODB_URI
            value: "mongodb://mongo:27017/"
